"""Tests for multipage app pages using Streamlit AppTest.

Smoke tests verify each page loads without errors when demo data is
present in session state (auto-generated by init_session_state).
"""

import pytest
from streamlit.testing.v1 import AppTest


@pytest.fixture
def app():
    """Create an AppTest instance from the main app entry point."""
    at = AppTest.from_file("app.py", default_timeout=30)
    at.run()
    return at


class TestSetupPage:
    """Tests for pages/setup.py rendering."""

    def test_loads_without_error(self, app):
        assert not app.exception, f"Setup page raised: {app.exception}"

    def test_displays_metrics(self, app):
        # init_session_state auto-generates demo data so metrics should exist
        assert len(app.metric) > 0


class TestLearnPage:
    """Tests for pages/learn.py rendering."""

    def test_loads_without_error(self, app):
        app.switch_page("pages/learn.py")
        app.run()
        assert not app.exception, f"Learn page raised: {app.exception}"


class TestPlayPage:
    """Tests for pages/play.py rendering."""

    def test_loads_without_error(self, app):
        app.switch_page("pages/play.py")
        app.run()
        assert not app.exception, f"Play page raised: {app.exception}"


class TestExplorePage:
    """Tests for pages/explore.py rendering."""

    def test_loads_without_error(self, app):
        app.switch_page("pages/explore.py")
        app.run()
        assert not app.exception, f"Explore page raised: {app.exception}"


class TestAnalyzePage:
    """Tests for pages/analyze.py rendering."""

    def test_loads_without_error(self, app):
        app.switch_page("pages/analyze.py")
        app.run()
        assert not app.exception, f"Analyze page raised: {app.exception}"
